### ISSUE TITLE
Node Red Flow

### ISSUE THREAD

**Issue by Exit2Studios** [drewbeer/poolBot#1]
Would you mind sharing your node red flow?

**Comment by drewbeer** [comment]
[poolbot-node-red.json.txt](https://github.com/drewbeer/poolBot/files/3598865/poolbot-node-red.json.txt)

here it is in all its glory, its very terrible. i still have a rewrite that is coming but at least you get how it works.

**Comment by drewbeer** [comment]
since this is no longer required with the newer version i'm going to close this, but old ones are documented.
